import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import RulesModal from "../../components/Rules";
import { socket } from "../../socket";
import "./Lobby.css";

const LobbyScreen: React.FC = () => {
  let navigate = useNavigate();
  const [showRules, setShowRules] = useState<boolean>(false);
  const [roomCode, setRoomCode] = useState<string>("");

  const newGame = async () => {
    const response = await socket.emitWithAck("create-room", "player 1");

    if (!response.success) {
      alert("Failed to create room");
      return;
    }

    navigate("/game", {
      state: { roomCode: response.roomCode, isOwner: true },
    });
  };

  const toggleRules = () => {
    setShowRules(!showRules);
  };

  const joinRoom = () => {
    if (roomCode.length !== 6) {
      alert("Room code must be 6 digits");
      return;
    }

    socket.emit("join-room", roomCode);

    socket.once("join-room-response", (success: boolean) => {
      if (!success) {
        alert("Room not found or full");
      } else {
        navigate("/game", { state: { roomCode: roomCode, isOwner: false } });
      }
    });
  };

  const sanitizeRoomCode = (event: React.ChangeEvent<HTMLInputElement>) => {
    let changed = event.target.value;
    if (/^\d*$/.test(changed) && changed.length <= 6) {
      setRoomCode(changed);
    }
  };

  // svgs generated by chatgpt
  return (
    <div className="lobby-screen-style">
      <div className="header">
        <button className="icon-button rules-icon" onClick={toggleRules}>
          <svg
            viewBox="0 0 24 24"
            fill="currentColor"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm1-13h-2v6h2V7zm0 8h-2v2h2v-2z" />
          </svg>
        </button>
        <h1 className="title">Welcome to Quick21</h1>
        <div className="profile">
          <img
            src="/assets/images/profile-icon-3.svg"
            alt="Profile Icon"         />

          <span>Player</span>
        </div>
      </div>

      <button className="new-game-button" onClick={newGame}>
        New Game
      </button>

      <div className="input-group">
        <input
          value={roomCode}
          onChange={sanitizeRoomCode}
          placeholder="Enter game code"
          maxLength={6}
        />
        <button onClick={joinRoom}>Join Game</button>
      </div>

      <span className="version-number">v1.0</span>

      {showRules && (
        <div className="overlay-style" onClick={() => setShowRules(false)}>
          <RulesModal onClose={() => setShowRules(false)} />
        </div>
      )}
    </div>
  );
};

export default LobbyScreen;
